# See https://github.com/Mic92/sops-nix
keys:
  - &users:
    - &lentilus 988659C39959183385845F0F6594ADA13130D0CD
  - &hosts:
    - &T480 age1awzjsmyuj7v6jnwqzddtg0n93cajul0vg7yenhmrke7w7kgwge3s0lxdq0
creation_rules:
  - path_regex: ^secrets/.*$
    key_groups:
    - age:
      - *T480
      pgp:
      - *lentilus

