#!/bin/bash

set -e

devpod up . --ide none
nix build /home/lentilus/git/nix-dotfiles/#homeConfigurations.vscode.activationPackage --impure -L

tries=0
while [ $tries -le 3 ]; do
    {
        # for some reason this likes to fail in the process
        # so we just wrap it with three tries
        nix copy --no-check-sigs --to ssh-ng:devpodtesting.devpod ./result
    }||{
        echo trying again...
        tries=$(( tries + 1 ))
    }
done

echo running activation
ssh devpodtesting.devpod 'hm="$(ls /nix/store | grep "home-manager-generation")"; /nix/store/${hm}/activate'
